language: php

php:
  - 5.3
  - 5.5

before_script:
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install --dev

script:
  - phpunit --exclude-group=none

branches:
  only:
      - master
      - develop

services:
    - mongodb
    - elasticsearch
